### ISSUE TITLE
Tough as Nails integration

### ISSUE THREAD

**Issue by Efimero** [KnightMiner/Ceramics#10]
Would it be possible to to allow the water interfaces on TAN work from your barrels? Right now when I right-click with an empty bottle nothing happens. I would expect it would give me a dirty water bottle and remove a bucket's worth from the barrel (or a third?)
It would also be cool if you could drink directly from the barrel.

**Comment by KnightMiner** [comment]
I looked into this a bit and the easiest way to implement this as an optional dependency would be using the Forge event and checking for my fluid handler. The thing is, by switching that check to any fluid handler (like buckets use) this would support the exact same thing you are suggesting with all tanks.

Based on that, I would suggest you bring this to TAN and ask for something that supports all tanks.
