### ISSUE TITLE
Client crash w/ Tinker's Con

### ISSUE THREAD

**Issue by Seth0067** [KnightMiner/Ceramics#11]
Hi there - thanks for checking this out, KnightMiner.  

Rewally looking forward to using your mod in my 1.11 pack, but I am getting a client crash with Tinker's Construct.  Removed TiCon (and the associated mods) and Ceramics loaded fine.

crash log paste
https://pastebin.com/R9bN3PAD

**Comment by KnightMiner** [comment]
Update Tinkers Construct, the version you are using is missing an interface I am using.

Apparently I was not explicit enough with my version dependency check (I forgot the Alpha builds were under 2.7.0) so Forge did not complain, but Ceramics requires at least 2.7.0.26.
