### ISSUE TITLE
Implement recipe return

### ISSUE THREAD

**Issue by Dilnu** [KnightMiner/Ceramics#12]
Hi there, I've noticed that your buckets don't default to being returned when used in recipes like vanilla buckets do. It seems like that might be a nice feature, it could even handle the cold fluids return items thing vs hot fluids do not which seems like it would be aesthetic.

**Comment by KnightMiner** [comment]
I'm pretty sure my bucket uses the same method that vanilla uses to place it in the inventory unless they coded it per recipe. I'll look into it when I get a chance.

**Comment by Dilnu** [comment]
Oh, my mistake I was also testing with forestry and that's the mod with the containers that aren't returned. Sorry.

**Comment by KnightMiner** [comment]
Are you saying my buckets are returned, or the vanilla ones are not?

**Comment by Dilnu** [comment]
Oh, I was being unclear.

I was testing a bunch of containers, the ones from Forestry are not returned.
Vanilla buckets and your buckets are returned.

I got confused because some other mods weren't respecting the code which has the items be returned, more specifically Botania's Runic Altar. That isn't your issue though.

**Comment by KnightMiner** [comment]
Ah, in that case I'll close this issue. Nice to already have the feature being suggested.
