### ISSUE TITLE
Feature Request: Add 1.12 Glazed Terracotta

### ISSUE THREAD

**Issue by Syndaryl** [KnightMiner/Ceramics#13]
1.12 adds "glazed terracotta" blocks, with bright decorative patterns; these are created by re-firing "stained clay" blocks (now renamed to "terracotta"). I suggest adding support for Glazed Terracotta for barrels and suchlike, possibly by re-firing the standard clay barrels as a parallel to the process for creating the actual glazed terracotta blocks. 
* If you can re-use the resource location for the minecraft textures, this would keep compatibility with texture packs.

**Comment by KnightMiner** [comment]
Weird thing about terracotta is it is intended to be rotated, so the barrels would always look like half a texture. Plus, I already have 70 different barrel blocks counting extensions and unfired...

**Comment by KnightMiner** [comment]
Closing in favor of #26
