### ISSUE TITLE
Can't remove water from Botania Petal Apothecary

### ISSUE THREAD

**Issue by SupaSloth** [KnightMiner/Ceramics#15]
Hello!

I am working in Minecraft 1.10.2 with the following mod versions.

Forge 12.18.3.2297
Botania r1.9-341
Ceramics 1.10.2-1.1.6b

Everything works great except that I can't seem to remove water from the petal apothecary with a clay bucket. I can put water in without issue. Just can't remove it.

Thanks!

**Comment by KnightMiner** [comment]
I just checked Botania's code, and based on [these lines](https://github.com/Vazkii/Botania/blob/1.10-final/src/main/java/vazkii/botania/common/block/BlockAltar.java#L187-L195), its hardcoded to vanilla buckets. I'd say report this to Botania as they should be using a fluid capability as they use one for insertion.

I do think both of us are no longer supporting 1.10 though, so good chance this will not be fixed until 1.12.

**Comment by SupaSloth** [comment]
Sounds good. Thanks for looking at it!

**Comment by KnightMiner** [comment]
I'm going to close this since its on botania's side. Feel free t9 link this issue from a botania one if it exists.
