### ISSUE TITLE
Clay armor not baking in 1.12

### ISSUE THREAD

**Issue by Syndaryl** [KnightMiner/Ceramics#16]
Mod version 1.3.1, forge 2441: I can't bake any of the clay armor pieces in the minecraft furnace :(
They don't shift-click into the furnace (as if they have no recipe), and JEI shows no uses for them.

**Comment by Syndaryl** [comment]
Actually, just noticed what is more like the problem:
I can use the old recipes of using raw clay to make unfired clay armor, instead of the new recipe to make unfired clay plates and make armor out of those. Why is unfired clay armor still in the game?

**Comment by KnightMiner** [comment]
I left it in to prevent from breaking old worlds. Also, It's technically an Easter egg now as it's rare to get amor with just one hit point, but it does occur to me it's easy to accidently craft. I'll add an uncrafting recipe in the next build.

**Comment by KnightMiner** [comment]
Latest build has a config to remove raw clay armor, plus a recipe to craft the armor back into clay.
