### ISSUE TITLE
Incompatibility with Gravel Ores on 1.11.2

### ISSUE THREAD

**Issue by Sunconure11** [KnightMiner/Ceramics#17]
https://github.com/elucent/GravelOres/issues/4

**Comment by KnightMiner** [comment]
Well, congradulations to myself for breaking things. Probably an item disabled in the config if I had to guess.

**Comment by KnightMiner** [comment]
Any chance you can link your full game logs? I seem to recall JEI catches this and logs an error which makes it a bit easier to find

Edit: nevermind, I found it. I'll see about pushing a build shortly as I assume this could break other mods as well.

**Comment by KnightMiner** [comment]
Build released as 1.2.3b
