### ISSUE TITLE
How does this line work without causing a null pointer exception?

### ISSUE THREAD

**Issue by TheFoss** [KnightMiner/Ceramics#19]
https://github.com/KnightMiner/Ceramics/blob/01d7be9eb627d548d5e2070b619c0795ce2da297/src/main/java/knightminer/ceramics/Ceramics.java#L147

When I implement this proxy.preInit section, pointing to an empty preInit section in CommonProxy, it returns a null pointer exception.  Are there any other lines of code here that need to be present for the proxy.preInit to work?

**Comment by TheFoss** [comment]
I should also mention that I have the

`public static CommonProxy proxy`

line in there, and proxy.preInit shows the it is pointing to the location in CommonProxy.

**Comment by TheFoss** [comment]
Nevermind.  I believe I have found the problem elsewhere.

**Comment by KnightMiner** [comment]
See [these lines](https://github.com/KnightMiner/Ceramics/blob/01d7be9eb627d548d5e2070b619c0795ce2da297/src/main/java/knightminer/ceramics/Ceramics.java#L76-L77). Basically, Forge creates an instance of one of those two classes based on whether we are the client or server and sets it to the proxy variable, the annotation is all you need.
