### ISSUE TITLE
Can't place torchs on top of ceramic walls

### ISSUE THREAD

**Issue by 252rer** [KnightMiner/Ceramics#20]
I can't see to place a torch on top of ceramic walls like you can with vanilla cobblestone walls.
Minecraft 1.10.2
Ceramic 1.1.6b

**Comment by KnightMiner** [comment]
Confirmed and fixed for 1.12. Seems torches were checking for vanilla walls specifically and not an instanceof check.

Not likely in 1.10 or 1.11 for a fix as I don't plan any more releases there except for major bugs.

**Comment by KnightMiner** [comment]
Fixed in 1.3.3. Forgot to close this issue.

I do not currently plan to backport this to 1.10.2 though unless a larger bug comes up, so unfortunately it will remain broken there.
