### ISSUE TITLE
[MC 1.10.2] Faucet missing?

### ISSUE THREAD

**Issue by craft90** [KnightMiner/Ceramics#21]
I can't seem to be able to find the porcelain faucet in the creative menu. Even with just Ceramics  1.1.6b in the mod folder it doesn't show up. Fresh JAR, same issue. New instance, same issue. And I can't see anything in the log about the mod itself. Only something about dependency on TiC?

**Comment by KnightMiner** [comment]
Porcelain faucets in 1.10 only exist if Tinkers Construct is installed. Update to 1.12 if you want them without TiC

**Comment by craft90** [comment]
I understand. That's bad tho cos Forge for 1.12 is still in Beta and the other mods I use aren't updated. Might wanna consider to annotate that on the Curse page, But thanks anyway,

**Comment by KnightMiner** [comment]
The Curse page is designed to describe the latest version. Its quite difficult to describe every latest version for every edition without making it difficult to understand for newcomers.

Also, 1.12 Forge has been out of Beta for awhile, and 1.11 (which also has this feature) has been non-Beta for longer. There just are not a lot of mod packs in either unfortunately.

**Comment by craft90** [comment]
I understand. It would have avoided this little misunderstanding though. :) I had TiC in the modpack but removed it as I tried to slim things down. Hence my confusion.

I have played in 1.12... but Forge still warns that it's experimental. So I don't know how stable it is.
