### ISSUE TITLE
Compat issues with Animania's cows

### ISSUE THREAD

**Issue by Tschipp** [KnightMiner/Ceramics#22]
We've encountered an issue that occurs when trying to milk Animania's cows with clay buckets:
Our cows have genders, only female cows give milk, but they all (also children) extend EntityCow. This causes both children and bulls to be milkable. 
Our cows also have special milk conditions, which are also ignored by the clay bucket.

So can you make more checks, or is there something we should change about our interact method? Sadly there's no handly interface for milking like for shearing...

**Comment by KnightMiner** [comment]
Unfortunately, there are no more checks I can add without a specific dependency as I use the exact same logic as vanilla last I checked.

Am I correct in assuming you are the mod author? If so, can determine what I would need for compatibility? (even if I just need to fire a custom event or you have an API for that, I'd like to avoid another full build dependency)

**Comment by KnightMiner** [comment]
What edition are you playing by the way? I assume this would be fixed by capnkirok/animania#42

**Comment by Tschipp** [comment]
Uh yeah I'm one of the devs. I guess it probably would be easier for me to do a check for your bucket, because I won't need a dependency for it. I'm gonna close this.
