### ISSUE TITLE
Could water flowing over a barrel fill it gradually?

### ISSUE THREAD

**Issue by dualcoding** [KnightMiner/Ceramics#25]
I figure this would allow for switching from normal block-size streams to Ceramics' miniatures nicely. Think big viaducts that switches to "taps" as it enters a building!

Great mod :+1:

**Comment by KnightMiner** [comment]
On the implementation side, I would rather not add anything which requires the barrel to become a ticking tile entity as I lose a large amount of efficiency then. I might be able to do something interesting using block ticks, but not really sure if it will be fast enough to be useful (them filling from rain is already extremely slow).

As far as gameplay, I am not really sure. On one side, it technically allows water duplication with little effort, but its also water so infinite water is trivial.

**Comment by dualcoding** [comment]
Interesting. I'm playing with Better With Mods hardcore buckets, which makes it impossible to move source blocks with the bucket. Water must be streamed from existing sourceblocks in aqueducts and actively pumped to go upwards... so streams of water are generally something you've earned!

It could definitely be cheaty if using something like Finite Water Control that allows you to _move_ source blocks but not duplicate them. In vanilla, as you say, infinite water is trivial anyway.

**Comment by KnightMiner** [comment]
Thinking over this more, I doubt this is something I will implement. Instead, what I want to add is the option for dispensers to fill fluid tanks using buckets, so you will be able to pull water from the world with a dispenser then full a barrel with it. Makes it require a little more infrastructure than just placing a block under flowing water and works better with finite fluids.
