### ISSUE TITLE
[Request] Forbid lava (+ other hot liquid pickup) and/or blacklist for fluids

### ISSUE THREAD

**Issue by SeriousCreeper** [KnightMiner/Ceramics#28]
Heya,

would it be possible to add an option to prevent things like lava buckets? Either any liquid that's considered hot would break the bucket immediately (and not just when emptying it), or have a blacklist of liquids that can't be picked up by a ceramic bucket. 

Cheers,
SC

**Comment by KnightMiner** [comment]
A config option to disallow hot liquid pickup would make sense (so basically anything that would normally break the bucket), I do not see myself adding a blacklist.

**Comment by KnightMiner** [comment]
Config option added in 1.3.4
