### ISSUE TITLE
Barrel / Bucket bug / sync issue

### ISSUE THREAD

**Issue by Leosky** [KnightMiner/Ceramics#30]
When i try to fill a clay barrel with a clay bucket filled with water, the level of water in the barrel increase but the tank still indicate empty on TOP. When if i log out / log in, the bucket look full but if i try to transfer water in a tank, it doesn't transfer anything and the barrel is empty.

**Comment by KnightMiner** [comment]
Versions? Also, is this only with clay buckets or do normal ones work?

**Comment by Leosky** [comment]
Its on losts souls modpack version 1.0.4, version 1.3.3b for 1.12.x

**Comment by KnightMiner** [comment]
Can you answer the second question as well?

**Comment by Leosky** [comment]
Ho sorry, i figured it's not a bug related to ceramics but with the container i was picking the water, it wasn't working correctly and had sync issue between client and server. I close this issue sorry for that.
