### ISSUE TITLE
You can only smelt unfired porcelain in a vanilla furnace.

### ISSUE THREAD

**Issue by ProsperCraft** [KnightMiner/Ceramics#31]
You can't use modded furnaces to cook the unfired procelain.

You CAN, however, use them to smelt unfired porcelain barrels

**Comment by KnightMiner** [comment]
Which modded furnaces are giving you issues? I have seen several packs with modded furnaces that work fine

**Comment by ProsperCraft** [comment]
The recipe only shows a vanilla furnace in JEI.(this is part of the problem)

It does not work in a thermal expansion redstone furnace which was the first one I tried, then looked up the recipe.
It does work in a mek, futurepack and Industrial Forgoing (I had not tried them because the recipe didn't show)

**Comment by KnightMiner** [comment]
Alright, I've moved registering those recipes from postInit to the oredictionary event, so unless a mod is registering their oredictionary super late it should appear in other mod's furnaces.

**Comment by KnightMiner** [comment]
Recipes moved to event in 1.3.4
