### ISSUE TITLE
Clay bucket does not fill up Barrels

### ISSUE THREAD

**Issue by Dente222** [KnightMiner/Ceramics#33]
As the name says this buckets are not putting water into the barrel it shows that liquid is in but right click says that its empty.
Im suing v1.3.3b for 1.12.2 MC

**Comment by KnightMiner** [comment]
Are you on a server or single player? If a server, what type of server? What other mods do you have installed? What Forge version?

**Comment by Dente222** [comment]
Same thing happens on server and single game
Forge: v14.23.2.2611 for MC 1.12.2
Mods:
Better With Mods
Animania
Twilight Forest
Immersive Engineering and Petroleum
Waystones
Tough as nails
Iron chest
Enchiridion
Gravestones
Botania
Abyssal Craft: Added after Ceramics
Water Strainer
Antique Atlas
Bloodmoon
Client side Mods:
Just Enough Items
Sound Filters
Better FPS
Enhanced Visuals
Ambience+
and Sponge for Forge Server

**Comment by KnightMiner** [comment]
Does this happen on a normal Forge server? Preferably, reproduce with a minimal mod list so I can track down the issue.

**Comment by KnightMiner** [comment]
Closing for lack of response as I have been unable to reproduce this at all
