### ISSUE TITLE
Game Crashed when Right-click with armor in my hand to put it on...

### ISSUE THREAD

**Issue by Fireztonez** [KnightMiner/Ceramics#34]
Hello, I have a problem with the Fired Clay Armor;
When I right-click whit one pieces of the armor in my hand, the game completely crash and I need to restart the complete Modpack. This armor is needed for my Modpack, where the leather is take a multiple multiple day's to have, so the Fired Clay Armor and unfired Clay Armor is the 2 realy early game in my pack.

I test with a pack with pratically just your mod and couple other utillity mods, like JEI, crafttweaker, etc, and the same problem append.

Minecraft 1.12.2
Ceramics v. 1.12-1.3.3b
Forge 14.23.2.2616
Java: 8 (1.8.0_161-b12 64bit)

Crash Log: https://gist.github.com/Fireztonez/124fc08ec5a5cf38f332533ffa9fd80b

**Comment by KnightMiner** [comment]
According to your crash report, this is a Primal Core issue, they don't like that my armor has a null sound (which I've seen other mods do before). Since I've never had issues in vanilla, it sounds like a Primal Core issue. Report to them.

**Comment by Fireztonez** [comment]
Thank's, I just test again with a new pack. installing just the real basic things and the game didn't crash with your armor, but when I add PrimalCore, the game start crashing with your armor...

So that's a Primal Core bug...

**Comment by An-Sar** [comment]
i've added a null check for the sound event and this fixed the problem, will be in the next primal release.

**Comment by KnightMiner** [comment]
Cool. I'll leave this issue open for now as a reminder to add a sound on my side, as I am not really sure why I left it out originally.

**Comment by KnightMiner** [comment]
Sounds added in 1.3.4
