### ISSUE TITLE
[1.12.2] Clay Bucket Texture Mapping

### ISSUE THREAD

**Issue by artdude543** [KnightMiner/Ceramics#35]
Heyo!

Currently working on creating texture support in Fanver for the mod, and I came across an issue with the bucket and fluid render. Where the fluid render is not mapping to the base bucket texture correctly and seems to be hardcoded cords. If you see in the image below

![image](https://user-images.githubusercontent.com/1885466/38309466-0c518142-3812-11e8-9b26-3c32a84020aa.png)

The texture is being loaded as the lava shape is matching the overlay but is being pushed up out of the base sprite. I believe I have done this correctly if you want the textures to test with I can send them over 😄 

Thanks!

**Comment by KnightMiner** [comment]
The bucket uses the same model as the Forge bucket. If you want to change the fluid shape, [modify the model](https://github.com/KnightMiner/Ceramics/blob/1.12/src/main/resources/assets/ceramics/blockstates/clay_bucket.json#L16) to point to a different contents texture than the Forge one.
