### ISSUE TITLE
[Suggestion] Early Game Storage

### ISSUE THREAD

**Issue by Priderino** [KnightMiner/Ceramics#38]
It would be nice to have some kind of Clay Vessels that would function like a Shulker Box, but with less space, for a simple early game storage.

**Comment by KnightMiner** [comment]
I merged this into #26, I like the idea of a clay urn which can act as an early game shulker box, but I also want it to work like urns from Terraria that break to drop items. Going to be trying out a design to grant both features, likely though use of silk touch to transport the filled urn.
