### ISSUE TITLE
Issue using clay water buckets with craft tweaker

### ISSUE THREAD

**Issue by Winddbourne** [KnightMiner/Ceramics#39]
The way that the the mod sets up the water bucket results in it being very difficult (I won't say impossible though I haven't figured it out) to use these buckets with craft tweaker. I wanted to add a recipe to make Earthworks mud using a clay water bucket and dirt blocks. 

Using recipe maker I wound up with an empty clay bucket being used. Using MT hand to manually get the ID this is what came up:

<ceramics:clay_bucket>.withTag({fluids: {FluidName: "water", Amount: 1000}})

That ID won't work in the script. I haven't tried <ceramics:clay_bucket.withTag({fluids: {FluidName: "water", Amount: 1000}})> but since that isn't how the mod itself pulls up the ID I doubt that would work.  

I may try to add the water bucket to ore dictionary to make the water buckets equivalent in recipes but . . .  that seems like it would either result in clay buckets being transmuted into iron; or wouldn't give back buckets at all. Both of which are bad options.

**Comment by KnightMiner** [comment]
Oredictionary does not support NBT. That will not solve the issue.

If you are trying to add a vanilla crafting recipe in CraftTweaker, it should work to make it NBT sensitive, you would have to ask on their Discord if the recipe is not working.

Honestly you should avoid treating fluid containers as items if you want the fluid for a recipe. A proper solution would be earthworks implementing something like MinecraftForge/MinecraftForge#4449. That is done in Immersive Engineering which allows my buckets to be used in making Treated Wood.

**Comment by josephcsible** [comment]
Given that MinecraftForge/MinecraftForge#4449 was closed unmerged back in January, is there no better solution than every mod implementing their own slightly different version of what it did? That seems really ugly.

**Comment by KnightMiner** [comment]
Unfortunately no, there is nothing I can do on my side without messy behavior which would still have to be implemented by each mod separately. Hopefully someone will pick that up again.
