### ISSUE TITLE
HarvestDropsEvent handler for clay shears throws NPE.

### ISSUE THREAD

**Issue by Leviathan143** [KnightMiner/Ceramics#4]
**Ceramics version:** 1.1.0
**Details:**
The crash occured when I walked in front of a Botania Mana Spreader with a Tripwire Damaging lens installed. I did not have clay shears in my inventory. I suspect that the NPE was caused by HarvestDropsEvent#harvester being null; according to the comment on that field, null is a valid value.
**[Crash](http://pastebin.com/sp8XcZ5N)**

**Comment by KnightMiner** [comment]
Fixed in version 1.1.0a as soon as it approves on CurseForge.
