### ISSUE TITLE
Buckets still picks sand up dispite config, does not break after picking up lava

### ISSUE THREAD

**Issue by Stormalisk** [KnightMiner/Ceramics#43]
Running Ceramics-1.12-1.3.5:

Currently have     
Allows the clay bucket to pick up sand and gravel, because why not? [default: true]
B:sand=false

Yet bucket is still able todo so.

Also, when the bucket is able to pick up lava it does not break after placing in survival mode.'

Running forge
1.12.2-forge1.12.2-14.23.5.2768

**Comment by KnightMiner** [comment]
Thanks for the report, looks like a couple of oversights during the bucket rewrite. Will be fixed in the next release (I'll try to make it sooner)

**Comment by Stormalisk** [comment]
It is no problem, thank you for the hard work!

**Comment by KnightMiner** [comment]
Fixed in 1.3.6, should be up on CurseForge shortly
