### ISSUE TITLE
Picking up milk with a bucket will not give the proper milk bucket

### ISSUE THREAD

**Issue by KnightMiner** [KnightMiner/Ceramics#44]
Due to the clay bucket rewrite, it seems picking up milk from in world or a fluid tank will give a clay bucket containing milk (NBT version) rather than the drinkable variety (metadata). [Relevant code](https://github.com/KnightMiner/Ceramics/blob/1.12/src/main/java/knightminer/ceramics/items/ItemClayBucket.java#L479-L489)

**Comment by Sunconure11** [comment]
https://github.com/Sunconure11/compitum-magia-issues/issues/10

Could this be connected?

**Comment by KnightMiner** [comment]
Not at all, you have some (likely core) mod doing something terrible to your registries, possibly preventing registration events. the part that references Cermics references an item that always exists so it's impossible to not be registered
