### ISSUE TITLE
Clay Bucket and Milk Clay Bucket

### ISSUE THREAD

**Issue by Shadowclaimer** [KnightMiner/Ceramics#47]
I'm attempting to rename these in my modpack to fit Atum's clay variant (Marl), the water, lava, and whatever that other bucket is rename fine, but the empty bucket and milk bucket I can't seem to get them renamed. I'm assuming its something with my CraftTweaker script and my own infinite stupidity, but I thought I'd bring it up here in-case its something in the localization pull or something that isn't working properly.

![image](https://user-images.githubusercontent.com/2214143/57184765-2e634f00-6e75-11e9-8a6f-fd975cf66877.png)

![image](https://user-images.githubusercontent.com/2214143/57184767-33c09980-6e75-11e9-92ce-acdc38e55b3c.png)

**Comment by KnightMiner** [comment]
Honestly, no idea why it would not work, but that is 100% the wrong way to rename an item. Like, sure, CraftTweaker can do it, but a mod such as resource loader with changing the .lang files will be so much more reliable. If I had to guess, the reason is because of the custom logic to make the names work, but it shouldn't be any different than the Forge bucket or most other dynamically named items do.

**Comment by Shadowclaimer** [comment]
That's good to know, just figured I'd check in here and see if I was breaking things somewhere or if this was maybe a known issue. I'm normally a mod dev, not a modpack dev, so kinda learning the ins and outs of all of this, and someone had mentioned it might be on your lang side that it wasn't working.

Regardless, thank you!

**Comment by KnightMiner** [comment]
Yeah, I just looked into the code and the way CraftTweaker does renames is attempting to find the lang key from the itemstack and replacing that key, which does not work for the bucket as it uses a formatted lang key. I am skipping overriding one method which overriding might make CraftTweaker's method work, but it still will never beat the designed method.

**Comment by Shadowclaimer** [comment]
Makes sense, thank you so much for your time and advice.
