### ISSUE TITLE
Clay Buckets with fluid stuck in ME Drive

### ISSUE THREAD

**Issue by Sunekaer** [KnightMiner/Ceramics#50]
FTB Issue tracker: https://github.com/FTBTeam/FTB-Builders-Paradise/issues/31

Hi,

Clay Buckets with fluid are stuck in ME Drive, Clay Buckets without fluid in can be taken out of the ME Drive without problems.

	appliedenergistics2-rv6-stable-6.jar
	Ceramics-1.12-1.3.7.jar

**Comment by KnightMiner** [comment]
What makes you think this is a cermaics issue? My clay buckets are no different than any other item with NBT, notably rhe forge bucket.

Have you tested this in a pack with just the two mods? Have you tried normal buckets? And have you reported this to AE?

**Comment by Sunekaer** [comment]
I created an issue here to start with as it doesnt happen with normal buckets with fluid in, to hear if you had any ideas or had seen this before

**Comment by Sunekaer** [comment]
and forgot to say it doesnt happen when only 
"appliedenergistics2-rv6-stable-6.jar
Ceramics-1.12-1.3.7.jar"
but it seems like you have seen this before, ill report back when I figure something out

**Comment by Sunekaer** [comment]
Okay its AstralSorcery, ill report it to them

**Comment by katubug** [comment]
@Sunekaer I'm having this same issue, can you tell me what suggested Astral Sorcery as the culprit?

**Comment by katubug** [comment]
Additionally, in the AS issue you mentioned that vanilla liquids are not affected by the bug? In my version, all filled buckets are affected.
