### ISSUE TITLE
[Suggestion] non-porcelain faucets/channels

### ISSUE THREAD

**Issue by inkdear** [KnightMiner/Ceramics#53]
Just faucets and channels to match the undyed clay barrels. It always feels like a thing that's missing, cosmetically, when I'm building with them. Thank you for reading!

**Comment by KnightMiner** [comment]
They actually exist in the current version if porcelain is disabled. I want to add them as a permanent feature, but I want them to have some unique behaviors.

My current plan is to wait until I port to 1.14. I plan to rework a few things, including disallowing hot fluids in clay barrels, requiring upgrading to porcelain. The clay faucets and channels will be added with the same limitation then.

**Comment by inkdear** [comment]
Ah, I see! Is there any chance of a 1.12 version just to give the option of having both at once, no functional changes?

**Comment by KnightMiner** [comment]
Probably not, I don't plan to add any new major features to 1.12 at the moment, plus with the way they are implemented in 1.12 if someone had porcelain disable before then updated it may break their world.

**Comment by inkdear** [comment]
Okay, thank you for responding!

**Comment by KnightMiner** [comment]
Added to latest 1.16 builds
