### ISSUE TITLE
no return is not supported for clay bucket

### ISSUE THREAD

**Issue by MeedoWorld** [KnightMiner/Ceramics#54]
hello i don't know if its issue or i am doing it wrong here is the code i don't want this return an empty bucket but it show error:
recipes.addShapeless(<ceramics:clay_bucket:1>.noReturn(), [<ceramics:clay_bucket>.withTag({fluids: {FluidName: "milk_friesian", Amount: 1000}}).onlyWithTag({fluids: {FluidName: "milk_friesian", Amount: 1000}})]);

**Comment by KnightMiner** [comment]
No return goes on the input, you have it on the output.

**Comment by MeedoWorld** [comment]
it worked ! thank you very much!
yes you right and should goes after NBT tag
solution :
recipes.addShapeless(<ceramics:clay_bucket:1>, [<ceramics:clay_bucket>.withTag({fluids: {FluidName: "milk_sheep", Amount: 1000}}).onlyWithTag({fluids: {FluidName: "milk_sheep", Amount: 1000}})**.noReturn**()]);
