### ISSUE TITLE
Unfired Porcelain Block Untextured w/ Creative Pick Block or TheOneProbe

### ISSUE THREAD

**Issue by nephatrine** [KnightMiner/Ceramics#55]
If I craft an unfired porcelain block (ceramics:clay_soft:0), it looks as it should. If I place that place into the world, it appears as it should visually and I get the correct drop when silk touching it, but TheOneProbe show the block's icon as an untextured block when looking at it and if I pick-block it in creative, I actually get that untextured block (ceramics:clay_soft:4).

**Comment by KnightMiner** [comment]
Looks like a sideeffect of making the clay block drop raw porcelain messed with the damage when dropping the block. Its an easy fix, but unsure of my plans for further 1.12 versions.

**Comment by KnightMiner** [comment]
Closing this as its been 2 years and I have not touched 1.12, safe to say I nevver will again.
