### ISSUE TITLE
Game wont start if porcelain or barrel are = false in config file

### ISSUE THREAD

**Issue by PrinceOfAmber** [KnightMiner/Ceramics#6]
Im trying to use this mod because the buckets and armor sound really cool.  I used the config file to disable the barrels and the decorative blocks but the game wont load.  Config file and log below

enabled {
    # Enables the clay armor, an early game alternative to leather [default: true]
    B:armor=true

    # Enables the clay barrel, a liquid tank that can be expanded upwards [default: true]
    B:barrel=false

    # Enables the clay bucket, an alternative to the iron bucket that breaks from hot liquids [default: true]
    B:bucket=true

    # Enables porcelain, a whiter clay that produces true colors when dyed [default: true]
    B:porcelain=false

    # Enables the clay shears, faster than iron shears but less duribility [default: true]
    B:shears=true
}

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.10-2.1.0.jar)
  LoadingPlugin (Quark-r1.0-56.jar)
  LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  LoadingPlugin (ChunkAnimator-MC1.9.4-1.2.jar)
  ForgelinPlugin (Forgelin-1.0.5.jar)
  dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 17/10/16 9:44 PM
Description: Initializing game

java.lang.IllegalArgumentException: Block registered to block color handler cannot be null!
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:174)
	at knightminer.ceramics.ClientProxy.init(ClientProxy.java:81)
	at knightminer.ceramics.Ceramics.init(Ceramics.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by KnightMiner** [comment]
Huh, I thought I fixed that, apparently I just did it with the model loader and not the color tinter.

**Comment by KnightMiner** [comment]
As a temporary fix, you can grab the older version from before I added barrels/porcelain, though you will lose shears as well (though barrels are cool, so I don't know why you would disable them :p)

**Comment by KnightMiner** [comment]
Fixed in version 1.1.2, which should be available on CurseForge any minute
