### ISSUE TITLE
No clay bucket texture.

### ISSUE THREAD

**Issue by CoolBean323** [KnightMiner/Ceramics#61]
Clay bucket, and variants with or water or lava have no texture. (Milk works)

 - Minecraft: 1.16.1
 - Ceramics: Newest version as of August 23 2020

**Comment by KnightMiner** [comment]
There is no newest version. Type in the version number you are playing.

What other mods do you have installed? And do you have any resource packs installed? If nether, I need a copy of your game logs to verify the cause.

**Comment by KnightMiner** [comment]
Closing for lack of response, it has no missing texture in my testing, so there is information you are not providing causing the missing texture.
