### ISSUE TITLE
Fluidsystem in 1.16.X

### ISSUE THREAD

**Issue by cyberpunkbln** [KnightMiner/Ceramics#62]
Hello,
short question: i don't see barrels and channels in the 1.16.x Versions? Are the fluid-system implemented in the newesr versions?
thx

**Comment by KnightMiner** [comment]
If something is not there, particularly on a beta build, assume not implemented yet. Closing as I have other ways to keep track of unimplemented features.

For a longer explanation, barrels need a small redesign, as I never liked how you obtained extensions. And channels/faucets need a rewrite for 1.13+ capability logic.
