### ISSUE TITLE
Clay buckets dont fill with caurldrens from more cauldrens mod

### ISSUE THREAD

**Issue by benbenlaw** [KnightMiner/Ceramics#66]
**Describe the bug**
Clay water buckets dont fill with caurldrens from more cauldrens mod

**Screenshots or crash report (if relevant)**

**Versions (please complete the following information):**
 - Minecraft: 1.16.4
 - Ceramics: latest

**Other mods required**

More caurldrens

**Comment by KnightMiner** [comment]
Means the more cauldrons mod does not respond to fluid handlers on interaction. Not much I can do about this from my side without writing special compatibility, in general mods accepting water buckets for filling should be more generic and accept any fluid container filled with water.

**Comment by KnightMiner** [comment]
Fixed in More Cauldrons side
