### ISSUE TITLE
Crash with rats mod

### ISSUE THREAD

**Issue by benbenlaw** [KnightMiner/Ceramics#67]
**Describe the bug**
Placing a milk bucket into a rats curdling station crashes the gane

**Screenshots or crash report (if relevant)**

**Versions (please complete the following information):**
 - Minecraft: 1.16.4
 - Ceramics: latest

**Other mods required**
Rats mod latest

**Comment by benbenlaw** [comment]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 1/10/21 12:11 PM
Description: Ticking block entity

java.lang.ClassCastException: net.minecraftforge.common.util.LazyOptional cannot be cast to net.minecraftforge.fluids.capability.IFluidHandlerItem
	at com.github.alexthe666.rats.server.entity.tile.TileEntityAutoCurdler.func_73660_a(TileEntityAutoCurdler.java:207) ~[rats:7.0.3-1.16.3] {re:classloading}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.alexthe666.rats.server.entity.tile.TileEntityAutoCurdler.func_73660_a(TileEntityAutoCurdler.java:207) ~[rats:7.0.3-1.16.3] {re:classloading}
-- Block entity being ticked --
Details:
	Name: rats:auto_curdler // com.github.alexthe666.rats.server.entity.tile.TileEntityAutoCurdler
	Block: Block{rats:auto_curdler}[facing=north]
	Block location: World: (272,64,261), Chunk: (at 0,4,5 in 17,16; contains blocks 272,0,256 to 287,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{rats:auto_curdler}[facing=north]
	Block location: World: (272,64,261), Chunk: (at 0,4,5 in 17,16; contains blocks 272,0,256 to 287,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}


-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:overworld
	Level spawn location: World: (256,64,256), Chunk: (at 0,4,0 in 16,16; contains blocks 256,0,256 to 271,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1932681 game time, 396722 day time
	Level name: Quest World Set Up
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}


-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_242, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), 
	Memory: 4576355696 bytes (4364 MB) / 6480723968 bytes (6180 MB) up to 15271460864 bytes (14564 MB)
	CPUs: 16
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16384m -Xms16384m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.29.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.29.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.29.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.29.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.29.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.29
	FML Language Providers: 
		javafml@35.1
		minecraft@1
		kotlinforforge@1.7.0
	Mod List: 
		rhino-1.7.13.9.jar                                |Rhino                         |rhino                         |1.7.13.9            |DONE      |NOSIGNATURE
		ftbessentials-1603.1.0.11.jar                     |FTB Essentials                |ftbessentials                 |1603.1.0.11         |DONE      |NOSIGNATURE
		item-filters-1604.2.2.19.jar                      |Item Filters                  |itemfilters                   |1604.2.2.19         |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.0.62.jar                           |Just Enough Items             |jei                           |7.6.0.62            |DONE      |NOSIGNATURE
		Tiny-Coal-1.16.4-1.0.0.jar                        |Tiny Coal                     |tinycoal                      |1.0.0               |DONE      |NOSIGNATURE
		woodenutilities-1.0.6-1.16.4.jar                  |Wooden Utilities              |woodenutilities               |1.0.5               |DONE      |NOSIGNATURE
		Space-Bosstools-1.16.4-3.6.jar                    |boss tools                    |boss_tools                    |3.3                 |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3b.jar                         |Create                        |create                        |mc1.16.3_v0.3b      |DONE      |NOSIGNATURE
		shutupexperimentalsettings-1.0.1.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.1               |DONE      |NOSIGNATURE
		Controlling-7.0.0.11.jar                          |Controlling                   |controlling                   |7.0.0.11            |DONE      |NOSIGNATURE
		Placebo-1.16.3-4.3.3.jar                          |Placebo                       |placebo                       |4.3.3               |DONE      |NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
		SimpleStorageNetwork-1.16.3-1.2.1.jar             |Simple Storage Network        |storagenetwork                |1.16.3-1.2.1        |DONE      |1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		ftb-gui-library-1604.1.1.26.jar                   |FTB GUI Library               |ftbguilibrary                 |1604.1.1.26         |DONE      |NOSIGNATURE
		Bookshelf-1.16.4-9.3.18.jar                       |Bookshelf                     |bookshelf                     |9.3.18              |DONE      |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		pneumaticcraft-repressurized-1.16.4-2.8.2-101.jar |PneumaticCraft: Repressurized |pneumaticcraft                |1.16.4-2.8.2-101    |DONE      |NOSIGNATURE
		ForgivingVoid_1.16.3-5.2.0.jar                    |Forgiving Void                |forgivingvoid                 |5.2.0               |DONE      |NOSIGNATURE
		TwerkItMeal-1.3.5.jar                             |TwerkItMeal                   |twerkitmeal                   |1.3.5               |DONE      |NOSIGNATURE
		Interactio-1.16.4-3.1.1.jar                       |Interactio                    |interactio                    |1.16.4-3.1.1        |DONE      |NOSIGNATURE
		WaterStrainer-1.16.3-10.0.0.jar                   |Water Strainer                |waterstrainer                 |1.16.3-10.0.0       |DONE      |NOSIGNATURE
		Toast-Control-1.16.3-4.3.0.jar                    |Toast Control                 |toastcontrol                  |4.3.0               |DONE      |NOSIGNATURE
		CauldronRecipes-1.16.4-5.0.3.jar                  |CauldronRecipes               |cauldronrecipes               |5.0.3               |DONE      |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		ImmersivePetroleum-1.16.4-3.1.0-2.jar             |Immersive Petroleum           |immersivepetroleum            |3.1.0-2             |DONE      |NOSIGNATURE
		ftb-teams-1604.1.0.13.jar                         |FTB Teams                     |ftbteams                      |1604.1.0.13         |DONE      |NOSIGNATURE
		ftb-chunks-1604.2.2.56.jar                        |FTB Chunks                    |ftbchunks                     |1604.2.2.56         |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.29-universal.jar                |Forge                         |forge                         |35.1.29             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		VendingMachine-1.16.2-1.0.0.3.jar                 |Vending Machine               |vm                            |1.0.0.3             |DONE      |NOSIGNATURE
		More-Cauldrons-1.16.3-1.4.6.jar                   |More Cauldrons                |morecauldrons                 |1.4.6               |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.29-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		cofh_core-1.16.3-1.1.6.jar                        |CoFH Core                     |cofh_core                     |1.1.6               |DONE      |NOSIGNATURE
		thermal_foundation-1.16.3-1.1.6.jar               |Thermal Series                |thermal                       |1.1.6               |DONE      |NOSIGNATURE
		theoneprobe-1.16-3.0.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.0.7          |DONE      |NOSIGNATURE
		thermal_innovation-1.16.3-1.1.7.jar               |Thermal Innovation            |thermal_innovation            |1.1.7               |DONE      |NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |DONE      |NOSIGNATURE
		ftb-quests-1604.1.1.21.jar                        |FTB Quests                    |ftbquests                     |1604.1.1.21         |DONE      |NOSIGNATURE
		ImmersiveEngineering-1.16.4-4.1.2-129.jar         |Immersive Engineering         |immersiveengineering          |1.16.4-4.1.2-129    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		valkyrielib-1.16.4-3.0.6.1.jar                    |ValkyrieLib                   |valkyrielib                   |3.0.6.1             |DONE      |NOSIGNATURE
		ftb-ranks-1604.1.1.9.jar                          |FTB Ranks                     |ftbranks                      |1604.1.1.9          |DONE      |NOSIGNATURE
		Botania-1.16.4-410.jar                            |Botania                       |botania                       |1.16.4-410          |DONE      |NOSIGNATURE
		gardenofglass-1.6.jar                             |Garden of Glass               |gardenofglass                 |1.6                 |DONE      |NOSIGNATURE
		DimensionAccessManager-1.16.4-1.0.0.jar           |Dimension Access Manager      |dimension_access_manager      |1.0.0               |DONE      |NOSIGNATURE
		defaultworldtype-1.16.3-2.0.1.jar                 |Default World Type            |defaultworldtype              |2.0.1               |DONE      |NOSIGNATURE
		easy_villagers-1.16.4-1.0.10.jar                  |Easy Villagers                |easy_villagers                |1.16.4-1.0.10       |DONE      |NOSIGNATURE
		curios-forge-1.16.4-4.0.3.3.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.3      |DONE      |NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |DONE      |NOSIGNATURE
		Mantle-1.16.4-1.6.43.jar                          |Mantle                        |mantle                        |1.6.43              |DONE      |NOSIGNATURE
		rats-7.0.3-1.16.3.jar                             |Rats                          |rats                          |7.0.3               |DONE      |NOSIGNATURE
		itemcollectors-1.0.9-mc1.16.4.jar                 |Item Collectors               |itemcollectors                |1.0.9               |DONE      |NOSIGNATURE
		ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |DONE      |NOSIGNATURE
		thermal_cultivation-1.16.3-1.1.6.jar              |Thermal Cultivation           |thermal_cultivation           |1.1.6               |DONE      |NOSIGNATURE
		baubley-heart-canisters-1.16.4-1.0.0.jar          |Baubley Heart Canisters       |bhc                           |1.0                 |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		AkashicTome-1.4-14.jar                            |Akashic Tome                  |akashictome                   |1.4-14              |DONE      |NOSIGNATURE
		thermal_expansion-1.16.3-1.1.6.jar                |Thermal Expansion             |thermal_expansion             |1.1.6               |DONE      |NOSIGNATURE
		Ceramics-1.16.4-1.5.2.jar                         |Ceramics                      |ceramics                      |1.5.2               |DONE      |NOSIGNATURE
		ftb-ultimine-1603.1.1.13.jar                      |FTB Ultimine                  |ftbultimine                   |1603.1.1.13         |DONE      |NOSIGNATURE
		usefulhats-1.9.3-1.16.2+.jar                      |Useful Hats                   |usefulhats                    |1.9.3-1.16.2+       |DONE      |NOSIGNATURE
		tombstone-1.16-6.2.3.jar                          |Corail Tombstone              |tombstone                     |1.16-6.2.3          |DONE      |NOSIGNATURE
		Quark-r2.4-290.jar                                |Quark                         |quark                         |r2.4-290            |DONE      |NOSIGNATURE
		Apotheosis-1.16.3-4.4.1.jar                       |Apotheosis                    |apotheosis                    |4.4.1               |DONE      |NOSIGNATURE
		obfuscate-0.5.1-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.5.1               |DONE      |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		globaldataandresourcepacks-1.16.4-1.7.4.jar       |Global Data- & Resourcepacks  |globaldataandresourcepacks    |1.16.4-1.7.3        |DONE      |NOSIGNATURE
		thermal_locomotion-1.16.3-1.1.6.jar               |Thermal Locomotion            |thermal_locomotion            |1.1.6               |DONE      |NOSIGNATURE
		architectury-1.2.70-forge.jar                     |Architectury                  |architectury                  |1.2.70              |DONE      |NOSIGNATURE
		kubejs-1604.3.4.140-forge.jar                     |KubeJS                        |kubejs                        |1604.3.4.140        |DONE      |NOSIGNATURE
		kubejs-thermal-1604.1.0.5.jar                     |KubeJS Thermal                |kubejs_thermal                |1604.1.0.5          |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		ice_ice_baby-1.16.4-3.0.1.jar                     |Ice Ice Baby                  |ice_ice_baby                  |3.0.1               |DONE      |NOSIGNATURE
		solcarrot-1.16.3-1.9.8.jar                        |Spice of Life: Carrot Edition |solcarrot                     |1.16.3-1.9.8        |DONE      |NOSIGNATURE
		Corail-Backpack-1.16.4-025.jar                    |Corail Backpack               |corail_backpack               |1.16.4-020          |DONE      |NOSIGNATURE
		kubejs-immersive-engineering-1604.1.0.12.jar      |KubeJS Immersive Engineering  |kubejs_immersive_engineering  |1604.1.0.12         |DONE      |NOSIGNATURE
		CobbleForDays-1.3.1.jar                           |Cobble For Days               |cobblefordays                 |1.3.1               |DONE      |NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |NOSIGNATURE
		Morph-o-Tool-1.4-25.jar                           |Morph-o-Tool                  |morphtool                     |1.4-25              |DONE      |NOSIGNATURE
	Crash Report UUID: 7679b42a-7c48-4cd9-bffe-777a4e3dbd34
	Patchouli open book context: n/a
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:ftbguilibrary (incompatible), mod:rhino, mod:ftbultimine (incompatible), mod:mousetweaks, mod:ftbessentials, mod:ftbranks (incompatible), mod:architectury, mod:itemfilters (incompatible), mod:interactio, mod:jei, mod:kubejs, mod:botania, mod:gardenofglass, mod:ftbteams (incompatible), mod:ftbquests (incompatible), mod:ftbchunks (incompatible), mod:forge, mod:appleskin, mod:curios, mod:patchouli (incompatible), mod:ftbbackups (incompatible), mod:controlling, mod:create (incompatible), mod:globaldataandresourcepacks (incompatible), file/recipes, mod:theoneprobe, mod:twerkitmeal, mod:woodenutilities, mod:forgivingvoid (incompatible), mod:fastleafdecay (incompatible), mod:citadel (incompatible), mod:rats, mod:cofh_core (incompatible), mod:thermal (incompatible), mod:thermal_cultivation (incompatible), mod:thermal_expansion (incompatible), mod:kubejs_thermal, mod:thermal_locomotion (incompatible), mod:bookshelf, mod:cauldronrecipes, mod:morecauldrons, mod:waterstrainer, mod:mantle (incompatible), mod:ceramics (incompatible), mod:cobblefordays (incompatible), mod:tinycoal (incompatible), mod:easy_villagers, mod:vm, mod:pneumaticcraft, mod:usefulhats, mod:placebo (incompatible), mod:apotheosis (incompatible), mod:solcarrot (incompatible), mod:storagenetwork (incompatible), mod:thermal_innovation (incompatible), mod:autoreglib (incompatible), mod:tombstone, mod:quark (incompatible), mod:immersivepetroleum (incompatible), mod:immersiveengineering (incompatible), mod:kubejs_immersive_engineering, mod:toastcontrol (incompatible), mod:boss_tools, mod:obfuscate (incompatible), mod:shutupexperimentalsettings (incompatible), mod:valkyrielib, mod:ice_ice_baby (incompatible), mod:itemcollectors, mod:corail_backpack, mod:bhc (incompatible), mod:defaultworldtype, mod:akashictome, mod:morphtool (incompatible), mod:dimension_access_manager
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by KnightMiner** [comment]
Looks like a Rats bug, please report to them and link the issue here.

**Comment by KnightMiner** [comment]
5f7cef3 would have fixed this if the issue was on my side, so closing this as probably fixed in 1.6.1
