### ISSUE TITLE
NBT data being ignored

### ISSUE THREAD

**Issue by benbenlaw** [KnightMiner/Ceramics#69]
**Describe the bug**
adding crafting recipes using NBT data allows any filled bucket to be used

**Screenshots or crash report (if relevant)**
![image](https://user-images.githubusercontent.com/42780877/104631467-30defa00-5694-11eb-9692-f21dbe4d6777.png)
recipe should only allow empty buckets, yet any filled bucket is being used
![image](https://user-images.githubusercontent.com/42780877/104631488-39cfcb80-5694-11eb-8268-8148ec57f3aa.png)
recipe file

**Versions (please complete the following information):**
 - Minecraft: 1.16.4
 - Ceramics: latest

**Other mods required**
Interactio -in world crafting with data packs

List any other mods required to reproduce this issue. Test by running the game with minimal mods.

**Comment by KnightMiner** [comment]
A normal item input ignores NBT. You need to use an ingredient type that checks NBT. I think all you need is `"nbt": {}` next to the item, but that could vary with how they set up their serializer. This is not really an issue with my mod, so I suggest you ask on a support forum if you need help writing JSON for an ingredient with strict NBT checking or ask on the mod's help page how you make a ingredient NBT strict..

Also, **never** write "latest" as the version. There is no latest version. Write a version number or that information is useless. What I know to be the latest version and what you think are the latest version may not be the same, so write a useful number there.
