### ISSUE TITLE
Alternate Porcelain Recipe

### ISSUE THREAD

**Issue by esotericist** [KnightMiner/Ceramics#7]
I adore the aesthetics for porcelain (the tinted hardened clay in vanilla has always bugged me) but the particular recipe you have (clay ball + 2 bone meal per porcelain ball) is a bit steep to anyone who might be inclined to avoid combat.

Maybe something that doesn't involve mob drops? In real life, bisque porcelain is a mixture of kaolinite, feldspar, and flint. Diorite is, among other things comprised of feldspar...

This suggests some possible configurations with technically non-renewable yet readily accessible resources for non-combatants.

**Comment by KnightMiner** [comment]
Looking it up on Wikipedia, I see quartz is an alternative to bone ash for making porcelain, and gameplay wise that makes sense since quartz is primarily decorative, so I might add an alternate recipe using that.

**Comment by esotericist** [comment]
... if you mean 'nether quartz', that's even worse for me, because I avoid the nether. :(

BTW, flint = quartz.

**Comment by esotericist** [comment]
For clarity, the purpose of me making a suggestion was looking for 'safe' ways to get porcelain, because I don't see a reason why 'pretty blocks' has to mean 'dangerous to get'.

**Comment by KnightMiner** [comment]
I personally don't think flint makes sense gameplay wise given it is commonly used to make black or gray colored blocks, and diorite is quite solid to blend with the clay. Additionally, I don't want to trivialize porcelain in case I expend its uses to more than decoration, such as its heat resistant use.

In any case, the nether is quite safe, just don't punch pigmen and say in caves away from ghasts. :)

**Comment by KnightMiner** [comment]
I added a recipe using quartz, and now especially since I added oredict support with Ex Nihilo I doubt I will add a cheaper recipe than bone meal, so I'll close this issue.
