### ISSUE TITLE
Buckets of liquid used in crafting recipe uses buckets

### ISSUE THREAD

**Issue by benbenlaw** [KnightMiner/Ceramics#70]
**Describe the bug**
i added a recipe to create treatedwood from immersive engineerring
![image](https://user-images.githubusercontent.com/42780877/105838786-7a9adf00-5fc8-11eb-850f-ed5a5523aa04.png)

but the recipe consumes the bucket when it shouldnt the vanialla bucket is left in the crafting table

**Screenshots or crash report (if relevant)**

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Ceramics:  1.16.5 1.6.1

**Other mods required**

Immersive engineering and kubejs

**Comment by KnightMiner** [comment]
Crafting recipes are added using JSON, you shouldn't need KubeJS. I can tell you JSON recipes can do this task perfectly fine, so to me sounds like you need to talk to the KubeJS team and ask how to add a recipe matching NBT.
