### ISSUE TITLE
Allow faucets to pour into cauldrons.

### ISSUE THREAD

**Issue by Jason-c-o** [KnightMiner/Ceramics#71]
**Describe the idea**
Allow faucets and downward channels to pour into/connect to vanilla cauldrons.

**Describe why you think it fits in Ceramics**
Why wouldn't it?

**Comment by KnightMiner** [comment]
Because cauldrons hold three  1/3 bucket increments of water, and faucets output 240mb per second. 1/3 is not convertable to bucket values, so I would have to fill 1000mb at a time, which is excessively fast.

So no, won't add this.
