### ISSUE TITLE
Curseforge keeps rejecting my pack due to Non-CF mod, eramics-1.16.5-1.6.1.jar

### ISSUE THREAD

**Issue by ClaudiusMinimus** [KnightMiner/Ceramics#74]
Not sure this is a bug, but for some reason, Curseforge keeps rejecting your mod from my pack with the following message, which they have used more than once:

> The following files do not appear to belong to any mods on the approved Non-CurseForge list: server/mods/Ceramics-1.16.5-1.6.1.jar

Therefore, in order to get my pack approved, Cermanics has been removed and informed it is necessary to separately download Ceramics-1.16.5-1.6.1.jar. I also provide the link:
https://www.curseforge.com/minecraft/mc-mods/ceramics/files/3170842

It would sure be nice if CF would stop rejecting my pack due to Ceramics

**Comment by KnightMiner** [comment]
Talk to curseforge support, there's nothing I can do about their site. Nothing makes ceramics different from other mods on that regard.

**Comment by ClaudiusMinimus** [comment]
It seems you might have other pack devs experiencing the same issue. I had thought about using the other ceramics mod, but I like yours. Thought you might want to let them know so you don't lose other packs. It would not hurt to talk to them.

**Comment by KnightMiner** [comment]
This is the first I have heard of it. If any other pack devs have errors, they have not informed me.

You were diligent enough to report it to this issue tracker, so since you are the one experiencing this issue I suggest you [open a ticket with CurseForge](https://support.curseforge.com/en/support/home). I cannot do so as I do not make modpacks, so I cannot explain the problem you are seeing or help them if they want to debug the issue. This is a case I need a pack dev who knows how to make CurseForge pack devs if you are going to solve it. Feel free to reference me in the support ticket.

**Comment by ClaudiusMinimus** [comment]
I think I found the issue. Just checked the md5sum for Ceramics-1.16.5-1.6.1.jar I just downloaded from CF and the original one for my pack. The md5sum for both files was:

> 7dd8dcf35ccffb10ef7e52d56e908a1d

The md5sum shown on CF for the same file is:

> 79be374e3dc9a1b119310caa18bb1c49

Not sure why the md5sum does not match and is likely the reason the file was rejected. Would you please double-check this?

**Comment by KnightMiner** [comment]
The file I just downloaded from CurseForge has a md5sum of `79be374e3dc9a1b119310caa18bb1c49`, matches what CurseForge says. You sure you downloaded the Jar from Curseforge and not another source?

What method are you using to check the md5sum of the file?

**Comment by ClaudiusMinimus** [comment]
I just tested again twice and this time it matched. So I guess I must have had a corrupted download even though the jar file worked fine, and probably why the pack was rejected.
Thank you for your assistance in this!

**Comment by KnightMiner** [comment]
Bit more information on this, its not an isolated issue. A few modpack devs I've talked to are seeing this issue with other mods randomly. So yeah, up to CurseForge to fix it.
