### ISSUE TITLE
kiln mod support

### ISSUE THREAD

**Issue by 0Navis0** [KnightMiner/Ceramics#76]
And here is the list for the kiln now, I hope it can help.

- Minecraft
    - stone
    - smooth stone
    - smooth (red) sandstone
    - smooth quartz
    - (glazed) terracotta
    - (nether) brick
    - cracked (nether/stone/blackstone) bricks
    - glass
- Create
    - dolomite
    - gabbro
    - scoria
    - glass (from tiled/framed glass)
    - glass pane (from tiled/framed glass pane)
- Quark
    - smooth soul sandstone
    - smooth biotite
- Charm
    - refined obsidian
    - smooth glowstone
- Botania
    - metamorphic forest/plains/mountain/fungal/swamp/desert/taiga/mesa stone
- Ceramics
    - porcelain
    - dark/rainbow bricks
    - terracotta cistern/faucet/channel/plate
    - clay (cracked) bucket
- BiomesOPlenty
    - smooth white/orange/black sandstone
    - mud brick
- Environmental
    - mud brick
- Atmospheric
    - arid (red) smooth sandstone
- Endergic Expansion
    - emus brick
    - cracked endstone bricks
    - cracked purpur stone
- Nether Expansion
    - cracked (crimson/warped/ashen) nether bricks
- Outer End
    - cracked violite bricks
    - cracked violite tiles
- Lepton
    - cracked (red/ soul/arid/red arid/white/orange/black) sandstone
- Addendum
    - shulker swirl
- Flamboyant
    - glazed terracotta
- Simply Tea
    - tea pot/cup

**Comment by KnightMiner** [comment]
A laundry list of items to support is not a ton of help, as I'll have to research all those mods to find the expected output (and I don't have time to do that right now). If you want this in, I suggest making a list of input item ID, output item ID, and experience earned.

**Comment by 0Navis0** [comment]
It would be already nice to add the missing vanilla recipes for the cracked nether bricks and cracked backstone, smooth quartz slab.
