### ISSUE TITLE
mixed up recipe for porcelain from unfired cistern

### ISSUE THREAD

**Issue by Girithien** [KnightMiner/Ceramics#77]
**Describe the bug**
The "recycling" recipe for porcelain from an unfired porcelain cistern requires a clay cistern instead

**Screenshots or crash report (if relevant)**
https://gyazo.com/e46818fe1a85f93c670942a6b982308c

**Versions (please complete the following information):**
 - Minecraft: 1.16.4
 - Mantle: 1.6.79
 - Ceramics: 1.6.1

**Other mods required**
None

**Comment by KnightMiner** [comment]
Fixed in 1.6.2
