### ISSUE TITLE
Unable to hide buckets with Crafttweaker/JEITweaker, causes extra to show instead.

### ISSUE THREAD

**Issue by G-Stav** [KnightMiner/Ceramics#78]
**Describe the bug**
Trying to hide buckets causes two to show up instead of none.
This is the script used.
mods.jei.JEI.hideItem(<item:ceramics:clay_bucket>.withTag({fluid: "immersiveengineering:ethanol" as string}));

**Screenshots or crash report (if relevant)**
![2021-03-02_12 52 23](https://user-images.githubusercontent.com/18726116/109644105-585f2880-7b55-11eb-8fd5-2cff117bc823.png)

**Versions (please complete the following information):**
 - Minecraft: 1.16.4
 - Ceramics: 1.16.5-1.6.1

**Other mods required**
Crafttweaker 1.16.5-7.1.0.135
JEITweaker 1.16.5.1.0.1.13
List any other mods required to reproduce this issue. Test by running the game with minimal mods.

**Comment by KnightMiner** [comment]
I do everything I can on my side, that is registering the subtype adapter.

Verify you have the proper NBT, then try to test hiding with just JEI (you may need to install a mod to enable JEIs config GUI), if you cannot hide with JEI, it's a JEI bug. If you can, JEITweaker bug.

**Comment by KnightMiner** [comment]
Probably fixed in 1.6.3. If not, its a JEI bug
