### ISSUE TITLE
[Suggestion] Clay urns, Vases, Chimineas

### ISSUE THREAD

**Issue by Winddbourne** [KnightMiner/Ceramics#8]
Suggestions:

- One thing that would be nice to have here is the ability to make clay urns and vases to hold solid materials in the same way a chest does.  The obvious benefit here is that clay urns could have different decorative designs and motifs, could come in different colors, and just would be more appealing. 

- The minecraft flower pots are UGLY. A nice porcelain vase with different colors and decorative designs would be a much better place to put flowers. Smaller ones could hold things like poppies and dandilions while larger vases could hold the bigger flowers like roses. 

- Chimineyas are Mexican fireplaces made of clay. These could act like decorative furnaces. Here is a link to one: 

http://chimineasdirect.com/fired-up-designs-43-inch-iron-clad-clay-chiminea?gclid=CjwKEAiA_9nFBRCsurz7y_Px8xoSJAAUqvKCQwHS6i0ExXj1wBCTtxPAEhT3gG2UezYpDN-iYjHbvRoCK1Dw_wcB 

https://en.wikipedia.org/wiki/Chimenea

**Comment by KnightMiner** [comment]
I actually like a lot of these ideas. A more decorative version of the furnace would be nice, along with a clay storage block.

Not entirely sure about vases since I would then need to add support for modded flowers, but if I can find a way to get it working dynamically.

**Comment by Winddbourne** [comment]
You might try talking with Jaquadro on the flower issue I know he's solved it before in his mod "Garden Stuff". I think he's mostly focused on updating and getting "Storage Drawers" into a stable state for 1.10.2 right now but a collaboration between you two could be very interesting. 

One of the mods that eventually got folded into "Garden Stuff" is something called "Modular Flower Pots" which had a lot of clay pots, a potters wheel, and even stamps you could find to imprint your pots with different designs.

**Comment by KnightMiner** [comment]
Closing in favor of #26
