### ISSUE TITLE
CraftTweaker compat for the Kiln

### ISSUE THREAD

**Issue by joker876** [KnightMiner/Ceramics#80]
**Is your feature request related to a problem? Please describe.**
I would like to be able to add custom recipes to the Kiln, using CraftTweaker.

**Describe why you think it fits in Ceramics**
Because most big mods allow that kind of customization, and so should Ceramics

**Comment by KnightMiner** [comment]
There is customization, using data packs. I would highly advise you learning them as they give you a lot more customization.

I have no plans to add crafttweaker support myself. If someone pull requested it I would look 8nt9 it, but I already offer datapack support. Crafttweaker even has a way to add JSON for recipes so you can add your own "support" via.l a function

**Comment by joker876** [comment]
What about KubeJS compatibility?

**Comment by KnightMiner** [comment]
How is that different? I support datapacks. Anything that is not a datapack I will not write compat for, so only if someone else writes comap.

**Comment by MarkHardwick-EM** [comment]
KubeJS is supported through custom data pack insertion e.g.

`event.custom({
    type: 'ceramics:kiln',
    ingredient: Item.of('minecraft:clay_ball').toJson(),
    result: Item.of('minecraft:brick').withCount(2).toResultJson(),
    experience: 0.3,
    cookingTime: 100
  })`
