### ISSUE TITLE
Drinkable fluids can't be drunk in clay bucket

### ISSUE THREAD

**Issue by 0Navis0** [KnightMiner/Ceramics#81]
I notably think about milk.

**Comment by KnightMiner** [comment]
There is no forge API for drinkable fluids. So no easy way to solve this problem. Probably won't be fixed.

**Comment by 0Navis0** [comment]
Oh yeah it's pretty annoying. I hope that forge will be able to provide an api for that in the future. I suppose the only way for now is to make everything by yourself.

**Comment by KnightMiner** [comment]
After updating code related to buckets, this might be feasible on 1.18+, so will look into it again in the future. Let me know which mods on 1.18 have drinkable buckets as a point of reference.
