### ISSUE TITLE
Null pointer exception on faucets while siphoning Starlight

### ISSUE THREAD

**Issue by Tyrogandio** [KnightMiner/Ceramics#85]
I have two setups of four Lightwells from Astral Sorcery with Liquid Hoppers from Pneumatic Craft pumping Starlight into a Clay Barrel (with extension) from your mod. From each barrel I have a Porcelain Faucet over a Porcelain Channel path. Each faucet is hooked up to a constant redstone signal. As soon as I place a Rock Crystal in one of the wells, the client crashes and corrupts the save file. I'm unsure of the state of the barrels in terms of volume, but the lightwells were empty at the time.
Removal of the redstone feed to the faucets prevents the issue.

**Screenshots or crash report**
[crash-2022-03-15_12.33.07-server.txt](https://github.com/KnightMiner/Ceramics/files/8253484/crash-2022-03-15_12.33.07-server.txt)
![2022-03-15_12 55 02](https://user-images.githubusercontent.com/101644617/158383946-a00e6d51-bd37-4ba1-8106-661d9082d2b9.png)

**Versions:**
 - Minecraft: 1.12.2
 - Ceramics: 1.12-1.3.7b

**Other mods required**
 - Astral Sorcery: 1.12.2-1.10.27
 - PneumaticCraft: Repressurized: 1.12.2-0.11.15-398
 
 I am aware that a similar issue has been reported previously (https://github.com/KnightMiner/TinkersComplement/issues/43) but I am under the impression this was marked as fixed.
 In a related subject, the redstone signal does not always work triggering the faucets. In fact I've only managed to automate the faucet pouring in the two faucets from the plain clay tanks. The faucet on the light blue porcelain tank (on the lower right of the provided screenshot) never triggered autonomously. I am unsure of which one is the expected behavior as I have not found anything online to explain how I can automate the faucets without clocks.

**Comment by KnightMiner** [comment]
This issue had to be fixed separately in both tinkers and ceramics faucets, if one is causing you issues use the other.

I have no real desire to put more effort into 1.12 at this point, I've moved onto 1.18 for the most part so dropping support for older versions
